### ISSUE TITLE
^^ BLACKBEARD roadmap ^^

### ISSUE THREAD

**Issue by negamaxi** [pathephone/pathephone-desktop#60]
...and all we need to do is:

**features**
- [x] ability to add more than one album to playlist
- [x] ability to clear playlist
- [x] shuffle
- [x] repeat
- [x] take default tracks metadata from the file itself
- [x] drag'n'drop files
- [x] donate modal
- [x] search on albums
~~ignorelist for deleted albums~~
~~save album to my library~~
- [x] tray icon
~~endless discover feed~~
- [x] current time in player

**BREAKING**
- [x] audio-metadata (?)
  - [x] extract audio metadata to instance
  - [x] display audio metadata in albums view

gears:
- [x] get rid of SemanticUI
- [x] custom audio player (?)
- [x] stress test on 100+ albums (tested on 30 000)
---
Roadmap is a subject to change, therefore FELL FREE TO SHARE YOUR OPINION BELOW.

**Comment by DEgITx** [comment]
меня тут неожиданно осенило, вроде же нету еще текущего время в плеере что играется, чуть что можешь на меня повесить

**Comment by negamaxi** [comment]
Да тоже думал. Имхо надо вместо длительности обратный отсчёт сделать.

**Comment by negamaxi** [comment]
closed by #170
